// Noirly Calculator — aligned with Noirly AlgoLab palette

export const lightColors = {
  background:                '#ffffff',
  surface:                   '#f8fafc',
  surfaceDim:                '#ffffff',
  surfaceBright:             '#f1f5f9',
  surfaceContainerLowest:    '#ffffff',
  surfaceContainerLow:       '#f8fafc',
  surfaceContainer:          '#f8fafc',
  surfaceContainerHigh:      '#f1f5f9',
  surfaceContainerHighest:   '#e2e8f0',
  surfaceVariant:            '#f1f5f9',
  surfaceTint:               '#0284c7',
  onSurface:                 '#0f172a',
  onSurfaceVariant:          '#64748b',
  onBackground:              '#0f172a',
  inverseSurface:            '#0f172a',
  inverseOnSurface:          '#ffffff',
  outline:                   '#cbd5e1',
  outlineVariant:            '#e2e8f0',
  primary:                   '#0284c7',
  onPrimary:                 '#ffffff',
  primaryContainer:          '#0284c7',
  onPrimaryContainer:        '#ffffff',
  inversePrimary:            '#38bdf8',
  primaryFixed:              '#e0f2fe',
  primaryFixedDim:           '#0284c7',
  onPrimaryFixed:            '#ffffff',
  onPrimaryFixedVariant:     '#0369a1',
  secondary:                 '#64748b',
  onSecondary:               '#ffffff',
  secondaryContainer:        '#f1f5f9',
  onSecondaryContainer:      '#64748b',
  secondaryFixed:            '#64748b',
  secondaryFixedDim:         '#475569',
  onSecondaryFixed:          '#ffffff',
  onSecondaryFixedVariant:   '#94a3b8',
  tertiary:                  '#ea580c',
  onTertiary:                '#ffffff',
  tertiaryContainer:         '#ffedd5',
  onTertiaryContainer:       '#ea580c',
  tertiaryFixed:             '#ea580c',
  tertiaryFixedDim:          '#c2410c',
  onTertiaryFixed:           '#ffffff',
  onTertiaryFixedVariant:    '#fdba74',
  error:                     '#ef4444',
  onError:                   '#ffffff',
  errorContainer:            '#fee2e2',
  onErrorContainer:          '#ef4444',
} as const;

export const darkColors = {
  background:                '#0b0f19',
  surface:                   '#111827',
  surfaceDim:                '#0b0f19',
  surfaceBright:             '#1f2937',
  surfaceContainerLowest:    '#0b0f19',
  surfaceContainerLow:       '#111827',
  surfaceContainer:          '#111827',
  surfaceContainerHigh:      '#1f2937',
  surfaceContainerHighest:   '#334155',
  surfaceVariant:            '#1f2937',
  surfaceTint:               '#38bdf8',
  onSurface:                 '#f1f5f9',
  onSurfaceVariant:          '#94a3b8',
  onBackground:              '#f1f5f9',
  inverseSurface:            '#f1f5f9',
  inverseOnSurface:          '#0b0f19',
  outline:                   '#475569',
  outlineVariant:            '#334155',
  primary:                   '#38bdf8',
  onPrimary:                 '#0b0f19',
  primaryContainer:          '#38bdf8',
  onPrimaryContainer:        '#0b0f19',
  inversePrimary:            '#0284c7',
  primaryFixed:              '#0c4a6e',
  primaryFixedDim:           '#38bdf8',
  onPrimaryFixed:            '#0b0f19',
  onPrimaryFixedVariant:     '#bae6fd',
  secondary:                 '#94a3b8',
  onSecondary:               '#0b0f19',
  secondaryContainer:        '#1f2937',
  onSecondaryContainer:      '#94a3b8',
  secondaryFixed:            '#94a3b8',
  secondaryFixedDim:         '#64748b',
  onSecondaryFixed:          '#0b0f19',
  onSecondaryFixedVariant:   '#cbd5e1',
  tertiary:                  '#fbbf24',
  onTertiary:                '#0b0f19',
  tertiaryContainer:         '#422006',
  onTertiaryContainer:       '#fbbf24',
  tertiaryFixed:             '#fbbf24',
  tertiaryFixedDim:          '#d97706',
  onTertiaryFixed:           '#0b0f19',
  onTertiaryFixedVariant:    '#fde68a',
  error:                     '#ef4444',
  onError:                   '#ffffff',
  errorContainer:            '#450a0a',
  onErrorContainer:          '#fca5a5',
} as const;

export type Colors = Record<keyof typeof lightColors, string>;

export function isDarkTheme(c: Colors): boolean {
  return c.background === darkColors.background;
}

const colors: Colors = lightColors;
export default colors;
