// Noirly Calculator — White · Black · Deep Red

export const lightColors = {
  background:                '#FFFFFF',
  surface:                   '#FFFFFF',
  surfaceDim:                '#f0f0f0',
  surfaceBright:             '#FFFFFF',
  surfaceContainerLowest:    '#FFFFFF',
  surfaceContainerLow:       '#f5f5f5',
  surfaceContainer:          '#eeeeee',
  surfaceContainerHigh:      '#e5e5e5',
  surfaceContainerHighest:   '#d9d9d9',
  surfaceVariant:            '#e5e5e5',
  surfaceTint:               '#B11226',
  onSurface:                 '#0F0F11',
  onSurfaceVariant:          '#333336',
  onBackground:              '#0F0F11',
  inverseSurface:            '#0F0F11',
  inverseOnSurface:          '#FFFFFF',
  outline:                   '#aaaaaa',
  outlineVariant:            '#cccccc',
  primary:                   '#B11226',
  onPrimary:                 '#FFFFFF',
  primaryContainer:          '#B11226',
  onPrimaryContainer:        '#FFFFFF',
  inversePrimary:            '#7a0d1a',
  primaryFixed:              '#fce4e7',
  primaryFixedDim:           '#B11226',
  onPrimaryFixed:            '#FFFFFF',
  onPrimaryFixedVariant:     '#7a0d1a',
  secondary:                 '#0F0F11',
  onSecondary:               '#FFFFFF',
  secondaryContainer:        '#e5e5e5',
  onSecondaryContainer:      '#0F0F11',
  secondaryFixed:            '#0F0F11',
  secondaryFixedDim:         '#333336',
  onSecondaryFixed:          '#FFFFFF',
  onSecondaryFixedVariant:   '#aaaaaa',
  tertiary:                  '#0F0F11',
  onTertiary:                '#FFFFFF',
  tertiaryContainer:         '#e5e5e5',
  onTertiaryContainer:       '#0F0F11',
  tertiaryFixed:             '#0F0F11',
  tertiaryFixedDim:          '#333336',
  onTertiaryFixed:           '#FFFFFF',
  onTertiaryFixedVariant:    '#aaaaaa',
  error:                     '#B11226',
  onError:                   '#FFFFFF',
  errorContainer:            '#fce4e7',
  onErrorContainer:          '#B11226',
} as const;

export const darkColors = {
  background:                '#0F0F11',
  surface:                   '#0F0F11',
  surfaceDim:                '#0a0a0c',
  surfaceBright:             '#1c1c1f',
  surfaceContainerLowest:    '#0a0a0c',
  surfaceContainerLow:       '#141417',
  surfaceContainer:          '#1a1a1e',
  surfaceContainerHigh:      '#222227',
  surfaceContainerHighest:   '#2c2c32',
  surfaceVariant:            '#222227',
  surfaceTint:               '#e8364d',
  onSurface:                 '#F0F0F2',
  onSurfaceVariant:          '#B0B0B8',
  onBackground:              '#F0F0F2',
  inverseSurface:            '#F0F0F2',
  inverseOnSurface:          '#0F0F11',
  outline:                   '#555560',
  outlineVariant:            '#333340',
  primary:                   '#e8364d',
  onPrimary:                 '#FFFFFF',
  primaryContainer:          '#B11226',
  onPrimaryContainer:        '#FFFFFF',
  inversePrimary:            '#fce4e7',
  primaryFixed:              '#4a0a13',
  primaryFixedDim:           '#e8364d',
  onPrimaryFixed:            '#FFFFFF',
  onPrimaryFixedVariant:     '#fce4e7',
  secondary:                 '#F0F0F2',
  onSecondary:               '#0F0F11',
  secondaryContainer:        '#2c2c32',
  onSecondaryContainer:      '#F0F0F2',
  secondaryFixed:            '#F0F0F2',
  secondaryFixedDim:         '#B0B0B8',
  onSecondaryFixed:          '#0F0F11',
  onSecondaryFixedVariant:   '#555560',
  tertiary:                  '#F0F0F2',
  onTertiary:                '#0F0F11',
  tertiaryContainer:         '#2c2c32',
  onTertiaryContainer:       '#F0F0F2',
  tertiaryFixed:             '#F0F0F2',
  tertiaryFixedDim:          '#B0B0B8',
  onTertiaryFixed:           '#0F0F11',
  onTertiaryFixedVariant:    '#555560',
  error:                     '#e8364d',
  onError:                   '#FFFFFF',
  errorContainer:            '#4a0a13',
  onErrorContainer:          '#fce4e7',
} as const;

export type Colors = Record<keyof typeof lightColors, string>;

const colors: Colors = lightColors;
export default colors;
