// Noirly Calculator — aligned with noirlyTheme

import { noirlyTheme } from './noirly-theme';

const { dark: d, light: l } = noirlyTheme;

export const lightColors = {
  background:                l.background,
  surface:                   l.surface,
  surfaceDim:                l.surface,
  surfaceBright:             l.surfaceVariant,
  surfaceContainerLowest:    l.surface,
  surfaceContainerLow:       l.surfaceVariant,
  surfaceContainer:          l.surface,
  surfaceContainerHigh:      l.surfaceVariant,
  surfaceContainerHighest:   l.divider,
  surfaceVariant:            l.surfaceVariant,
  surfaceTint:               l.primary,
  onSurface:                 l.textPrimary,
  onSurfaceVariant:          l.textSecondary,
  onBackground:              l.textPrimary,
  inverseSurface:            l.textPrimary,
  inverseOnSurface:          l.surface,
  outline:                   l.border,
  outlineVariant:            l.divider,
  primary:                   l.primary,
  onPrimary:                 l.textPrimary,
  primaryContainer:          l.primary,
  onPrimaryContainer:        l.textPrimary,
  inversePrimary:            d.primary,
  primaryFixed:              l.primarySoft,
  primaryFixedDim:           l.primaryHover,
  onPrimaryFixed:            l.textPrimary,
  onPrimaryFixedVariant:     l.textSecondary,
  secondary:                 l.textMuted,
  onSecondary:               l.surface,
  secondaryContainer:        l.surfaceVariant,
  onSecondaryContainer:      l.textSecondary,
  secondaryFixed:            l.textMuted,
  secondaryFixedDim:         l.textSecondary,
  onSecondaryFixed:          l.surface,
  onSecondaryFixedVariant:   l.textMuted,
  tertiary:                  l.warning,
  onTertiary:                l.textPrimary,
  tertiaryContainer:         l.primarySoft,
  onTertiaryContainer:       l.warning,
  tertiaryFixed:             l.warning,
  tertiaryFixedDim:          l.warning,
  onTertiaryFixed:           l.textPrimary,
  onTertiaryFixedVariant:    l.warning,
  error:                     l.error,
  onError:                   l.surface,
  errorContainer:            l.primarySoft,
  onErrorContainer:          l.error,
} as const;

export const darkColors = {
  background:                d.background,
  surface:                   d.surface,
  surfaceDim:                d.background,
  surfaceBright:             d.surfaceVariant,
  surfaceContainerLowest:    d.background,
  surfaceContainerLow:       d.surface,
  surfaceContainer:          d.surface,
  surfaceContainerHigh:      d.surfaceVariant,
  surfaceContainerHighest:   d.divider,
  surfaceVariant:            d.surfaceVariant,
  surfaceTint:               d.primary,
  onSurface:                 d.textPrimary,
  onSurfaceVariant:          d.textSecondary,
  onBackground:              d.textPrimary,
  inverseSurface:            d.textPrimary,
  inverseOnSurface:          d.background,
  outline:                   d.border,
  outlineVariant:            d.divider,
  primary:                   d.primary,
  onPrimary:                 d.background,
  primaryContainer:          d.primary,
  onPrimaryContainer:        d.background,
  inversePrimary:            l.primaryHover,
  primaryFixed:              d.primarySoft,
  primaryFixedDim:           d.primary,
  onPrimaryFixed:            d.background,
  onPrimaryFixedVariant:     d.textSecondary,
  secondary:                 d.textMuted,
  onSecondary:               d.background,
  secondaryContainer:        d.surfaceVariant,
  onSecondaryContainer:      d.textSecondary,
  secondaryFixed:            d.textMuted,
  secondaryFixedDim:         d.textSecondary,
  onSecondaryFixed:          d.background,
  onSecondaryFixedVariant:   d.textMuted,
  tertiary:                  d.warning,
  onTertiary:                d.background,
  tertiaryContainer:         d.primarySoft,
  onTertiaryContainer:       d.warning,
  tertiaryFixed:             d.warning,
  tertiaryFixedDim:          d.warning,
  onTertiaryFixed:           d.background,
  onTertiaryFixedVariant:    d.warning,
  error:                     d.error,
  onError:                   d.textPrimary,
  errorContainer:            d.primarySoft,
  onErrorContainer:          d.error,
} as const;

export type Colors = Record<keyof typeof lightColors, string>;

export function isDarkTheme(c: Colors): boolean {
  return c.background === darkColors.background;
}

const colors: Colors = lightColors;
export default colors;
